### ISSUE TITLE
Time elapsed is not recognizing the finish

### ISSUE THREAD

**Issue by ChrisChasm** [Pray4Movement/prayer-global-porch#188]
<img width="542" alt="Screenshot 2023-02-27 at 9 53 19 AM" src="https://user-images.githubusercontent.com/7318348/221628475-d91e693e-0cf4-41b5-921b-3d8956cf4c8e.png">
<img width="1448" alt="Screenshot 2023-02-27 at 9 56 01 AM" src="https://user-images.githubusercontent.com/7318348/221628767-520e56ef-6fb5-45e6-95a7-57adfe6cee92.png">

The calculation I am guessing is from start to now, when it should be from start to completed.

**Comment by squigglybob** [comment]
@ChrisChasm Looking at the laps, the reason is that they don't have an end_time, and so I think the system is defaulting to now()

I'll update the system to make sure that an end_time and date are put into the lap when it is completed.
It will be doing that for laps when they are recurring laps.

In the meantime, if you know what date ICOM and Northside finished their laps, then we can put that date into the lap, so that it calculates it correctly

**Comment by squigglybob** [comment]
Fix for this is already in place in the code.
Just needed to manually add the end_date and end_time on the live laps
