### ISSUE TITLE
Can't access exit from custom map

### ISSUE THREAD

**Issue by ChrisChasm** [Pray4Movement/prayer-global-porch#43]
You can't access the exit link at the bottom of a custom map on mobile screen any more.

![Screenshot 2022-11-15 at 8 29 00 AM](https://user-images.githubusercontent.com/7318348/201941890-c71254f1-b17f-4a19-a0ab-5d1489ed2db5.jpeg)

**Comment by squigglybob** [comment]
I noticed this on my wifes small phone screen.
There's another element of this where the offcanvas is not scrollable.

Was it scrollable before? If so I can find out what changed, otherwise I'll look at how to implement scrolling offcanvas.

It also affects the location details offcanvas on a small screen
