### ISSUE TITLE
User Profile Mockups

### ISSUE THREAD

**Issue by ChrisChasm** [Pray4Movement/prayer-global-porch#81]
### Discussed in https://github.com/Pray4Movement/prayer-global-porch/discussions/80

<div type='discussions-op-text'>

<sup>Originally posted by **ChrisChasm** November 28, 2022</sup>
Registration
Login
Offcanvas - Logged Out
Offcanvas - Logged In
Main Profile Page
Profile (Manage Page)
Prayers (Manage Page)
Challenges (Manage Page)
New Private Challenge
New Public Challenge

----

The page transition would be a left and right transition experience. From the main page, a tap on the profile row would transition to the profile page to the right, and the back arrow would bring navigation back to the main page. This navigation is separate from the offcanvas navigation.

----

<img width="358" alt="Screenshot 2022-11-28 at 2 46 56 PM" src="https://user-images.githubusercontent.com/7318348/204388177-d8dd3796-e4e2-4b6a-a135-b974f70ee4ce.png">
<img width="356" alt="Screenshot 2022-11-28 at 2 47 13 PM" src="https://user-images.githubusercontent.com/7318348/204388200-820a3a0b-fcb3-42ef-981e-084b22cf8648.png">
<img width="356" alt="Screenshot 2022-11-28 at 2 47 22 PM" src="https://user-images.githubusercontent.com/7318348/204388220-bea86072-34e9-480e-92b3-f4b19aa27c03.png">
<img width="356" alt="Screenshot 2022-11-28 at 2 47 35 PM" src="https://user-images.githubusercontent.com/7318348/204388233-5e389a3f-43b1-4811-8827-ee47623452c4.png">
<img width="357" alt="Screenshot 2022-11-28 at 2 55 02 PM" src="https://user-images.githubusercontent.com/7318348/204389332-bca1a10f-d86e-49e8-b15e-e22a9a9accd7.png">
<img width="359" alt="Screenshot 2022-11-28 at 2 48 00 PM" src="https://user-images.githubusercontent.com/7318348/204388331-3eef756a-5804-477f-a79b-399d2e3bc7c4.png">
<img width="357" alt="Screenshot 2022-11-28 at 2 48 09 PM" src="https://user-images.githubusercontent.com/7318348/204388341-e149f749-e997-44b8-b72b-ff61b88938c6.png">
<img width="358" alt="Screenshot 2022-11-28 at 2 48 24 PM" src="https://user-images.githubusercontent.com/7318348/204388348-c88a4dad-6c57-40b0-902e-8f8960ad3f0a.png">
<img width="358" alt="Screenshot 2022-11-28 at 2 48 34 PM" src="https://user-images.githubusercontent.com/7318348/204388356-308e5bc6-021b-4a25-8bdd-24fb1be58d5d.png">
<img width="359" alt="Screenshot 2022-11-28 at 2 48 44 PM" src="https://user-images.githubusercontent.com/7318348/204388364-06ef08bc-74a5-47dd-b322-ca837d8f23b8.png">
</div>

**Comment by squigglybob** [comment]
Awesome!! 🎉  This looks really cool.

I have a tonne of questions and suggestions. I'll note some down here for later.

### Registration

1. Is it ok if I merge the 2 password fields and put a "view password" button to reduce the registration fields?
2. I remember us talking about an auto-suggested Location box. Do we need to have it here? or can we just leave it in the profile page for them to find when they have a poke around?

### Prayers

1. I just randomly chose orange as a colour for the "my prayers" parts of the activity logs.  Could we firm up the colour that we actually want to use to represent a user in the activity, and therefore probably also on this log?
2. Need to discuss badge system

### Challenges

1. Can they leave the end date unfilled in? or should there be something more explicit to make the challenge ongoing?
2. Would we need another page for managing a challenge?

#### Manage Challenges

(This could be a seperate PR)

Could contain
* stats
* members
* activity 
* tools to promote the challenge, invite links etc.
* ability to message the group periodically with Push notifications

### AOQ

1. Are we still having a map button to take them to their own map?
2. Are you thinking that the profile/prayers/challenges pages would be in an offcanvas rather than a new page?

**Comment by prykon** [comment]
This looks great! Some comments and ideas...

- Typeahead in the location field when you register
- Add a login with Google button
- Language selection dropdown in the user settings even if currently disabled
- Are we going to have a section for all the collected badges or are we just going to show the current badge?
- Can we assign users an avatar and then show it in the map instead of the prayer warrior icon?

**Comment by squigglybob** [comment]
## registration

1. Keep the 2 password boxes, but not massively fixed on this. We can sort this out when we do the login/registration plugin part of this
2. We could have a "This is where we think you are ... <changeButton>"

## prayers

1. Let's steer away from using red, amber, green colours for anything except the infographics, maybe purple?

## challenges

1. Either have a button to specify the type, or allow the end date to be blank, I would favour more explicit direction, particularly if later we have other types of challenges.
5. Yes we will need another page to manage the challenges, this would need to be wireframed

NB private means not listed on our list, not that the urls are private

## badges

could be streak
could be milestones of prayed for certain thing.
could be time based for just a year.

For now let's just have a milestone badge for places prayed for
1, 5, 10, 50, 100, 500, 1000

## personal map

pause on this one.

sometimes it's ok to have functions outside the on map loader

## nav structure

fly over offcanvas on mobile for prayers/challenges/etc.
see how it looks on desktop...

Other options could be having it in a modal, or on desktop having a split screen design similar to DT metrics pages.

**Comment by corsacca** [comment]
Personal challenges:
Can we make this more of a list the user can chose from:
- Pray each location in the world
- Pray 15 minutes a day
- etc

The name, start and end date are confusing if the user doesn't know what a challenge is.

**Comment by squigglybob** [comment]
> The name, start and end date are confusing if the user doesn't know what a challenge is.
> 
> Time ranges can be added once one of those is selected?

yeah I'm thinking the same way as well.

Some kind of button group for the types of challenges, and then give the details to fill in once they have chosen.

At the moment, the 2 types of challenge would be

* Time restricted (with an end date)
* Ongoing (no end date)

and we can add more later.

I like the idea of the one's that you suggested, and then the app could have reminders with local notifications to reach their goal
